package Models;

// Generated Oct 10, 2017 7:08:11 PM by Hibernate Tools 4.3.1



/**
 * Employee generated by hbm2java
 */
public class AssignRole  implements java.io.Serializable {


     private int employeeid;
     private int role;

    public AssignRole() {
    }

    public AssignRole(int employeeid, int role) {
       this.employeeid = employeeid;
       this.role = role;
    }
   
    public int getEmployeeid() {
        return this.employeeid;
    }
    
    public void setEmployeeid(int employeeid) {
        this.employeeid = employeeid;
    }

    public int getRole() {
        return this.role;
    }
    
    public void setRole(int role) {
        this.role = role;
    }




}


