package Models;
// Generated Oct 10, 2017 7:08:11 PM by Hibernate Tools 4.3.1



/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private int employeeid;
     private String name;
     private int role;

    public Employee() {
    }

    public Employee(int employeeid, String name, int role) {
       this.employeeid = employeeid;
       this.name = name;
       this.role = role;
    }
   
    public int getEmployeeid() {
        return this.employeeid;
    }
    
    public void setEmployeeid(int employeeid) {
        this.employeeid = employeeid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getRole() {
        return this.role;
    }
    
    public void setRole(int role) {
        this.role = role;
    }




}


