package Models;
//import javax.persistence.Entity;
//import javax.persistence.GeneratedValue;
//import javax.persistence.Id;
// Generated Oct 10, 2017 7:08:11 PM by Hibernate Tools 4.3.1



/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


    //@Id @GeneratedValue
     private int roleid;
     private String title;

    public Role() {
    }

    public Role(int roleid, String title) {
       this.roleid = roleid;
       this.title = title;
    }
   
    public int getRoleid() {
        return this.roleid;
    }
    
    public void setRoleid(int roleid) {
        this.roleid = roleid;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }




}


